name: 'Build and Deploy to Cloud Run'
#
on:
  push:
    branches: [main]

jobs:

  call-security-scan:
    uses:  ani-menase-dvarim/devops/.github/workflows/ci.yml@main
    permissions:
      actions: read
      contents: read
      security-events: write  # Mandatory for CodeQL results
    secrets: inherit 
